export const horseOwnerAccount = {
  email: "owner@gmail.com",
  password: "Owner@123",
  user: {
    id: "owner-001",
    userId: "owner-001",
    username: "owner_demo",
    email: "owner.demo@horseracing.vn",
    role: "OWNER",
    fullName: "Nguyễn Hoàng Minh",
    phone: "0909123456",
  },
  // JWT giả lập (alg=none) để state auth local hoạt động khi reload
  token:
    "eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJzdWIiOiJvd25lci0wMDEiLCJyb2xlIjoiT1dORVIiLCJleHAiOjQxMDA5MDg4MDAsImVtYWlsIjoib3duZXIuZGVtb0Bob3JzZXJhY2luZy52biJ9.",
};

export const horses = [
  {
    id: "h1",
    name: "Golden Thunder",
    breed: "Thoroughbred",
    age: 5,
    weight: 480,
    color: "Hồng mã",
    health: "Tốt",
    healthTone: "green",
    wins: 8,
    races: 14,
    image: null,
    jockey: "Nguyễn Văn A",
    status: "Đang hoạt động",
  },
  {
    id: "h2",
    name: "Silver Storm",
    breed: "Arabian",
    age: 4,
    weight: 460,
    color: "Bạch mã",
    health: "Trung bình",
    healthTone: "gold",
    wins: 5,
    races: 10,
    image: null,
    jockey: "Trần Văn B",
    status: "Đang hồi phục",
  },
  {
    id: "h3",
    name: "Dark Knight",
    breed: "Quarter Horse",
    age: 6,
    weight: 510,
    color: "Hắc mã",
    health: "Tốt",
    healthTone: "green",
    wins: 12,
    races: 18,
    image: null,
    jockey: null,
    status: "Đang hoạt động",
  },
];

export const tournaments = [
  {
    id: "t1",
    name: "Vietnam Grand Prix 2026",
    location: "Phú Thọ Racecourse, TP.HCM",
    startDate: "2026-06-15",
    endDate: "2026-06-20",
    deadline: "2026-06-01",
    entryFee: 5000000,
    prizePool: 500000000,
    status: "Đang mở đăng ký",
    statusTone: "green",
    maxHorses: 120,
    registeredHorses: 87,
    description: "Giải đua ngựa lớn nhất miền Nam năm 2026",
  },
  {
    id: "t2",
    name: "Saigon Derby Spring Cup",
    location: "Saigon Racecourse",
    startDate: "2026-07-10",
    endDate: "2026-07-12",
    deadline: "2026-06-25",
    entryFee: 3000000,
    prizePool: 200000000,
    status: "Đang mở đăng ký",
    statusTone: "green",
    maxHorses: 80,
    registeredHorses: 45,
    description: "Giải đua ngựa mùa xuân truyền thống",
  },
  {
    id: "t3",
    name: "Hanoi Championship 2026",
    location: "Gia Lâm Racecourse, Hà Nội",
    startDate: "2026-08-05",
    endDate: "2026-08-08",
    deadline: "2026-07-20",
    entryFee: 4000000,
    prizePool: 350000000,
    status: "Sắp mở",
    statusTone: "gold",
    maxHorses: 100,
    registeredHorses: 0,
    description: "Giải đua danh giá tại thủ đô",
  },
];

export const registrations = [
  {
    id: "r1",
    tournament: "Vietnam Grand Prix 2026",
    horse: "Golden Thunder",
    jockey: "Nguyễn Văn A",
    raceNo: "R3",
    raceTime: "14:30",
    raceDate: "2026-06-16",
    entryFee: 5000000,
    status: "Approved",
    statusTone: "green",
    checkedIn: false,
  },
  {
    id: "r2",
    tournament: "Saigon Derby Spring Cup",
    horse: "Dark Knight",
    jockey: null,
    raceNo: "R1",
    raceTime: "10:00",
    raceDate: "2026-07-10",
    entryFee: 3000000,
    status: "Pending",
    statusTone: "gold",
    checkedIn: false,
  },
  {
    id: "r3",
    tournament: "Vietnam Grand Prix 2026",
    horse: "Silver Storm",
    jockey: "Trần Văn B",
    raceNo: "R1",
    raceTime: "09:00",
    raceDate: "2026-06-15",
    entryFee: 5000000,
    status: "Completed",
    statusTone: "blue",
    checkedIn: true,
  },
];

export const jockeys = [
  {
    id: "j1",
    name: "Nguyễn Văn A",
    age: 28,
    experience: 8,
    wins: 45,
    races: 112,
    winRate: 40.2,
    ranking: 3,
    license: "VN-JK-001",
    status: "Sẵn sàng",
    statusTone: "green",
    assigned: "Golden Thunder",
  },
  {
    id: "j2",
    name: "Trần Văn B",
    age: 32,
    experience: 12,
    wins: 68,
    races: 180,
    winRate: 37.8,
    ranking: 5,
    license: "VN-JK-002",
    status: "Sẵn sàng",
    statusTone: "green",
    assigned: "Silver Storm",
  },
  {
    id: "j3",
    name: "Lê Minh C",
    age: 25,
    experience: 4,
    wins: 18,
    races: 60,
    winRate: 30.0,
    ranking: 12,
    license: "VN-JK-007",
    status: "Bận",
    statusTone: "red",
    assigned: null,
  },
  {
    id: "j4",
    name: "Phạm Quang D",
    age: 30,
    experience: 10,
    wins: 55,
    races: 145,
    winRate: 37.9,
    ranking: 4,
    license: "VN-JK-004",
    status: "Sẵn sàng",
    statusTone: "green",
    assigned: null,
  },
];

export const payments = [
  {
    id: "p1",
    tournament: "Vietnam Grand Prix 2026",
    horse: "Golden Thunder",
    type: "Entry Fee",
    amount: 5000000,
    status: "Đã thanh toán",
    statusTone: "green",
    date: "2026-05-20",
    method: "Chuyển khoản",
  },
  {
    id: "p2",
    tournament: "Saigon Derby Spring Cup",
    horse: "Dark Knight",
    type: "Entry Fee",
    amount: 3000000,
    status: "Chờ thanh toán",
    statusTone: "gold",
    date: null,
    method: null,
  },
  {
    id: "p3",
    tournament: "Vietnam Grand Prix 2026 (R1)",
    horse: "Silver Storm",
    type: "Tiền thưởng",
    amount: 15000000,
    status: "Đã nhận",
    statusTone: "green",
    date: "2026-06-16",
    method: "Chuyển khoản",
  },
];

export const raceResults = [
  {
    id: "res1",
    tournament: "Vietnam Grand Prix 2026",
    race: "Race R3 · Chung kết",
    horse: "Golden Thunder",
    jockey: "Nguyễn Văn A",
    position: 1,
    finishTime: "1:42.35",
    prize: 50000000,
    date: "2026-06-16",
  },
  {
    id: "res2",
    tournament: "Saigon Derby 2025",
    race: "Race R2 · Bán kết",
    horse: "Silver Storm",
    jockey: "Trần Văn B",
    position: 3,
    finishTime: "1:44.12",
    prize: 10000000,
    date: "2025-11-20",
  },
  {
    id: "res3",
    tournament: "Hanoi Cup 2025",
    race: "Race R1",
    horse: "Dark Knight",
    jockey: "Phạm Quang D",
    position: 2,
    finishTime: "1:43.50",
    prize: 20000000,
    date: "2025-09-14",
  },
];

export const ownerNotifications = [
  {
    id: "n1",
    title: "Đăng ký đã được duyệt",
    body: "Golden Thunder đã được duyệt tham gia Vietnam Grand Prix 2026 · Race R3",
    time: "2 giờ trước",
    read: false,
    type: "success",
  },
  {
    id: "n2",
    title: "Nhắc nhở check-in",
    body: "Race R3 sẽ diễn ra vào ngày 16/06/2026 lúc 14:30. Vui lòng check-in trước 1 giờ.",
    time: "5 giờ trước",
    read: false,
    type: "warning",
  },
  {
    id: "n3",
    title: "Lời mời jockey",
    body: "Jockey Lê Minh C đã nhận lời mời cưỡi Dark Knight tại Saigon Derby Spring Cup",
    time: "1 ngày trước",
    read: true,
    type: "info",
  },
  {
    id: "n4",
    title: "Thanh toán thành công",
    body: "Đã thanh toán 5.000.000đ phí đăng ký Vietnam Grand Prix 2026",
    time: "2 ngày trước",
    read: true,
    type: "success",
  },
  {
    id: "n5",
    title: "Kết quả race",
    body: "Golden Thunder về nhất Race R3! Nhận thưởng 50.000.000đ",
    time: "3 ngày trước",
    read: true,
    type: "trophy",
  },
];

export const fmt = (n) =>
  new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND" }).format(
    n,
  );
