export { default as HomePage } from './HomePage'
export { default as AboutPage } from './AboutPage'
export { default as LoginPage } from './LoginPage'
export { default as RegisterPage } from './RegisterPage'
export { default as ForgotPasswordPage } from './ForgotPasswordPage'
export { default as ProfilePage } from './ProfilePage'
export { default as NotFoundPage } from './NotFoundPage'
export { default as DemoLogoutModal } from './DemoLogoutModal'
